import { NextResponse } from "next/server";
import type { Center } from "@/types/centers";

export const mockCenters: Center[] = [
  {
    id: "c1",
    name: "Dhaka Medical Center",
    location: { lat: 23.7261, lng: 90.3963 },
    distance: 1.2,
    vaccines: ["Pfizer", "Moderna", "Sinopharm"],
    slotsAvailable: 18,
    totalCapacity: 50,
    rating: 4.7,
    address: "Zahir Raihan Rd, Dhaka 1000",
    phone: "+880-2-55165088",
    hours: "8AM – 6PM",
    timeSlots: ["morning", "afternoon"],
    nextAvailableSlot: "Today, 2:30 PM",
    familyFriendly: true,
  },
  {
    id: "c2",
    name: "Square Hospital Vaccination Hub",
    location: { lat: 23.7516, lng: 90.3752 },
    distance: 2.8,
    vaccines: ["Pfizer", "AstraZeneca"],
    slotsAvailable: 4,
    totalCapacity: 40,
    rating: 4.5,
    address: "18/F West Panthapath, Dhaka 1205",
    phone: "+880-2-8159457",
    hours: "9AM – 5PM",
    timeSlots: ["morning", "afternoon", "evening"],
    nextAvailableSlot: "Today, 4:00 PM",
    familyFriendly: true,
  },
  {
    id: "c3",
    name: "Mugda General Hospital",
    location: { lat: 23.7337, lng: 90.4366 },
    distance: 4.1,
    vaccines: ["Sinopharm", "Covaxin"],
    slotsAvailable: 0,
    totalCapacity: 60,
    rating: 4.1,
    address: "Mugda, Dhaka 1214",
    phone: "+880-2-7272001",
    hours: "8AM – 4PM",
    timeSlots: ["morning"],
    nextAvailableSlot: "Tomorrow, 9:00 AM",
    familyFriendly: false,
  },
  {
    id: "c4",
    name: "Labaid Specialized Hospital",
    location: { lat: 23.7465, lng: 90.3714 },
    distance: 3.3,
    vaccines: ["Pfizer", "Moderna"],
    slotsAvailable: 22,
    totalCapacity: 45,
    rating: 4.8,
    address: "House 1, Road 4, Dhanmondi, Dhaka 1205",
    phone: "+880-2-9676356",
    hours: "8AM – 8PM",
    timeSlots: ["morning", "afternoon", "evening"],
    nextAvailableSlot: "Today, 11:00 AM",
    familyFriendly: true,
  },
  {
    id: "c5",
    name: "Shaheed Suhrawardy Medical College",
    location: { lat: 23.7699, lng: 90.3674 },
    distance: 5.6,
    vaccines: ["AstraZeneca", "Sinopharm", "Covaxin"],
    slotsAvailable: 7,
    totalCapacity: 80,
    rating: 4.2,
    address: "Sher-E-Bangla Nagar, Dhaka 1207",
    phone: "+880-2-9118608",
    hours: "9AM – 5PM",
    timeSlots: ["morning", "afternoon"],
    nextAvailableSlot: "Today, 3:30 PM",
    familyFriendly: true,
  },
  {
    id: "c6",
    name: "Uttara Crescent Hospital",
    location: { lat: 23.8759, lng: 90.3795 },
    distance: 8.4,
    vaccines: ["Pfizer", "Moderna", "AstraZeneca"],
    slotsAvailable: 31,
    totalCapacity: 50,
    rating: 4.6,
    address: "House 35, Road 7, Sector 4, Uttara, Dhaka 1230",
    phone: "+880-2-8931234",
    hours: "8AM – 7PM",
    timeSlots: ["morning", "afternoon", "evening"],
    nextAvailableSlot: "Today, 10:00 AM",
    familyFriendly: true,
  },
  {
    id: "c7",
    name: "Mirpur Community Health Center",
    location: { lat: 23.8041, lng: 90.3584 },
    distance: 6.9,
    vaccines: ["Sinopharm", "Covaxin"],
    slotsAvailable: 2,
    totalCapacity: 30,
    rating: 3.9,
    address: "Section 10, Mirpur, Dhaka 1216",
    phone: "+880-2-8012345",
    hours: "9AM – 4PM",
    timeSlots: ["morning"],
    nextAvailableSlot: "Tomorrow, 9:30 AM",
    familyFriendly: false,
  },
  {
    id: "c8",
    name: "Evercare Hospital Dhaka",
    location: { lat: 23.8223, lng: 90.4246 },
    distance: 9.1,
    vaccines: ["Pfizer", "Moderna"],
    slotsAvailable: 15,
    totalCapacity: 60,
    rating: 4.9,
    address: "Plot 81, Block E, Bashundhara R/A, Dhaka 1229",
    phone: "+880-2-55040000",
    hours: "8AM – 8PM",
    timeSlots: ["morning", "afternoon", "evening"],
    nextAvailableSlot: "Today, 1:00 PM",
    familyFriendly: true,
  },
];

export async function GET() {
  return NextResponse.json(mockCenters);
}
